# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HytaleDownloader < Formula
  desc "Native macOS ARM64 downloader for Hytale game files"
  homepage "https://github.com/AselionHYT/hytale-downloader"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/AselionHYT/hytale-downloader/releases/download/v1.0.0/hytale-downloader_1.0.0_darwin_arm64.tar.gz"
      sha256 "66bb759b0df2c0277bb4747a9a316153c8f87b4065a5be1a8ab1cf9c890d8b2a"

      def install
        bin.install "hytale-downloader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AselionHYT/hytale-downloader/releases/download/v1.0.0/hytale-downloader_1.0.0_linux_amd64.tar.gz"
      sha256 "299a0f873a3f8b4f7abef23d981d3c8831c2eaeee436df836e40433ece976bf6"
      def install
        bin.install "hytale-downloader"
      end
    end
  end

  test do
    system "#{bin}/hytale-downloader", "-version"
  end
end
