# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HytaleDownloader < Formula
  desc "Native macOS ARM64 downloader for Hytale game files"
  homepage "https://github.com/AselionHYT/hytale-downloader"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/AselionHYT/hytale-downloader/releases/download/v1.0.1/hytale-downloader_1.0.1_darwin_arm64.tar.gz"
      sha256 "5f8634a00f8caa214a0ee5af0ddadefee3c91275c2b0f4ee6ab18371450e37e2"

      def install
        bin.install "hytale-downloader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AselionHYT/hytale-downloader/releases/download/v1.0.1/hytale-downloader_1.0.1_linux_amd64.tar.gz"
      sha256 "9485da14783d42158249a19c577b248daa136f9b0a9ccb77932a223273abdad9"
      def install
        bin.install "hytale-downloader"
      end
    end
  end

  test do
    system "#{bin}/hytale-downloader", "-version"
  end
end
